version: '3.8'  # Optional, but can be kept for compatibility with older Docker Compose versions

services:
  app:
    build: .
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped  # Ensures the app restarts automatically unless explicitly stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Ensure this is set in your .env file
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped  # Ensures the database restarts automatically unless explicitly stopped

volumes:
  postgres_data: