version: '3.8'  # Optional, but can be kept for compatibility with older Docker Compose versions

services:
  app:
    build: .
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    